describe "Appointment API DELETE Request" do
  it "deletes an appointment found by id"
  it "deletes an appointment found by date"
  it "deletes an appointment found between dates"
  it "deletes an appointment found by year"
  it "deletes an appointment found by month"
  it "deletes an appointment found by day"
  it "deletes an appointment found by hour"
  it "deletes an appointment found by first_name"
  it "deletes an appointment found by last_name"
  it "deletes an appointment found by first_name and date"
  it "deletes an appointment found by last_name and date"
  it "deletes an appointment found by first_name and year"
  it "deletes an appointment found by first_name and month"
  it "deletes an appointment found by first_name and day"
  it "deletes an appointment found by first_name and hour"
  it "deletes an appointment found by last_name and year"
  it "deletes an appointment found by last_name and month"
  it "deletes an appointment found by last_name and day"
  it "deletes an appointment found by last_name and hour"
  it "gives an error if search returns multiple"
  it "gives an error if search returns none"
end
