describe "Appointment API GET Request" do
  it "displays a list of appointments"
  it "displays a single appointment by id"
  it "displays a list of appointments by date"
  it "displays a list of appointments between dates"
  it "displays a list of appointments by year"
  it "displays a list of appointments by month"
  it "displays a list of appointments by day"
  it "displays a list of appointments by hour"
  it "displays a list of appointments by first_name"
  it "displays a list of appointments by last_name"
  it "displays a list of appointments by first_name and date"
  it "displays a list of appointments by last_name and date"
  it "displays a list of appointments by first_name and year"
  it "displays a list of appointments by first_name and month"
  it "displays a list of appointments by first_name and day"
  it "displays a list of appointments by first_name and hour"
  it "displays a list of appointments by last_name and year"
  it "displays a list of appointments by last_name and month"
  it "displays a list of appointments by last_name and day"
  it "displays a list of appointments by last_name and hour"
end
